### ISSUE TITLE
Do you have any plans for being able to pass additional data to routes?

### ISSUE THREAD

**Issue by micmcg** [kyeotic/raviger#10]
Something similar to https://github.com/Paratron/hookrouter/blob/master/src-docs/pages/en/02_routing.md#passing-additional-data-to-route-functions (not necessarily that execution though)

**Comment by kyeotic** [comment]
@micmcg published under `0.5.0`. Contains a **breaking change** to `useRoutes*

**Comment by micmcg** [comment]
You're a machine!
Thanks 👍
