### ISSUE TITLE
Route matching hook

### ISSUE THREAD

**Issue by kyeotic** [kyeotic/raviger#107]
It would be nice if a component could get matching state for an individual route, or a set of routes. Unlike `useRoutes` this hook wouldn't be to render _content_, just to identify an active state for to apply "route-has-matched" behavior or styling to a component.

This came from the discussion in #105 

**Use Cases**
* A `<nav>` section, like a tab, that wanted active styling for a route. Like `<ActiveLink >`, but more general.
* A toolbar that might hide/display when a route or querystring-value was present

I can't think of any more off the top of my head, so use cases are welcome.

**Considerations**

* for a single route returning a boolean seems sufficient
* for a set of routes returning a string that matches the route could be awkward if there is a way to match on querystring-values
* this can already be achieved manually by combining `usePath` with `useQueryParams`. Is it worth introducing a new hook to serve this case?

**Comment by kristiandupont** [comment]
One not very obtrusive solution I can think of is to let `useRoutes` accept non-components as values and evaluate or just return them if a match is found.

I.e.:
```javascript

const activeTab = useRoutes({
  // Primitive types and objects are passed on
  '/home': 'home',

  // Functions are evaluated like they currently are, but non-components are accepted
  '/member/:memberId': ({memberId}) => `member-page-${memberId}`,
});

// activeTab is now a string.
```

That way, the hook that I was looking for could be expressed in this slightly weird manner:
```javascript
const isHome = useRoutes({ '/home': true });
```

I am not sure how elegant I think this is but it feels a simple way of building on the existing API.

**Comment by kyeotic** [comment]
That's an interesting idea, I need to think about it.

My first reaction is that using the API this way is awkward, specifically this bit: `'/home': true`. It has a feeling of _ceremony_ to it. It also overloads this hook's return value, instead of overloading its inputs. I generally think a separate function is a better way to achieve that.

Another idea would be 

```js
const routeName = useMatches([
  '/home',
  '/about',
])

const isHome = useMatch('/home')
```

**Comment by kyeotic** [comment]
I came up with another use case while coding this that requires a different return: getting the parameters from a match. Say you have a route like `/users/:userId` and you want to get the `userId` _if the route matches_. Unlike `useRoutes` you aren't rendering based on the result, you just want to get the parameters.

```js
// assuming path = /users/1
const params = useParameters('/users/:userId')
if (params) console.log(params) // { userId: 1 }

const [route, params] = useParameters(['/users/:userId', '/orders/:orderId'])
if (route) console.log(route, params) // '/users/:userId', { userId: 1 }
```
