### ISSUE TITLE
Navigate does not re-render component when redirecting to same page

### ISSUE THREAD

**Issue by nolan-m** [kyeotic/raviger#110]
When using the `navigate` function to redirect to the same page, the URL changes, but the component does not re-render. 
Reproduction steps listed in sandbox example.

[Example](https://codesandbox.io/s/modest-stallman-8jxuo?file=/example.js)

**Comment by kyeotic** [comment]
That's because there is nothing telling the component to re-render when you access the querystring directly. If you access it with the `useQueryParams` [hook it re-renders](https://codesandbox.io/s/wizardly-silence-5t8vv?file=/example.js).
