### ISSUE TITLE
useNavigate does not allow me to set a State

### ISSUE THREAD

**Issue by dave-irvine** [kyeotic/raviger#113]
If I use the `navigate()` function from https://kyeotic.github.io/raviger/navigate/, I can pass `state` as the 4th parameter and set some state. However if I call `useNavigate()` from https://kyeotic.github.io/raviger/use-navigate/, the function it returns does not allow `state` as the 4th parameter, but the docs say:

> The function returned by useNavigate has the same signature as the non-hook navigate function. 

Are the docs wrong or is the implementation incorrect?

Additionally, in the types that are generated for the project, the `navigate()` function has the following definitions:

```
export declare function navigate(url: string): void;
export declare function navigate(url: string, replace: boolean): void;
export declare function navigate(url: string, query: QueryParam | URLSearchParams): void;
export declare function navigate(url: string, query: QueryParam | URLSearchParams, replace: boolean): void;
export declare function navigate(url: string, queryOrReplace?: QueryParam | URLSearchParams | boolean | null, replace?: boolean): void;
export declare function navigate(url: string, query: QueryParam | URLSearchParams, replace: boolean, state: unknown): void;
```

this means there is no valid way to pass a `null` for the `query` and `replace` parameters when you try to also pass a `state` parameter.

**Comment by kyeotic** [comment]
I knew I missed something in the 3.0 list: I wanted to collapse `navigate` params to `url` and an _options_ object. The param handling here is a mess.

Unfortunately for `navigate` this isn't as easy as fixing the type annotations, since the `replaceOrQuery` uses `null` for checking which argument to replace.

For `useNavigate` it _is_ as easy as fixing the type annotations.

I should have some time this weekend to fix this and get the PR for #112 merged.

**Comment by dave-irvine** [comment]
Thanks for the fast reply, I switched to use `navigate()` directly for now and ignore the type error.

A followup question, is there an "official" way to consume the state and pass them as props to the route in `useRoutes()`? For now I hacked together a hook:

```
function useHistoryState() {
  const { state } = window.history;

  return state;
}
```

but it feels a bit out of place given everything else is done via raviger.

**Comment by kyeotic** [comment]
@dave-irvine I'm not sure whats going on with GitHub, I am not getting these notifications on the homepage anymore.

I'm going to create another issue to track this request and roll up all of these into a v4
