### ISSUE TITLE
Using navigate() can cause some strange issues

### ISSUE THREAD

**Issue by dave-irvine** [kyeotic/raviger#116]
Sandbox: https://codesandbox.io/s/keen-mahavira-jfxvk

In this example, I'm trying to return the user to the main page if somehow they arrive into my App on a sub-page in an unexpected state (no state in window.history).

To do this, on my sub-page, I check for the absence of `window.history.state`, and if its missing, I navigate back to `/`:

```
const { state } = window.history;

  if (!state) {
    navigate("/");
    return null;
  }
```

In my App, I log which path we are currently on:

```
console.log(usePath());
```

When the App is first loaded, we see `/` as the path, and if we navigate to the error page, we correctly see `/error` as the path.

But if we now *reload* the App while we are on the `/error` path, we correctly see 1 log for `/error`, and then we see `navigating to /`, and now *incorrectly* the path appears to be `/error` again, but the App renders the `Main` component. And now the app is stuck and further navigation is impossible.

https://user-images.githubusercontent.com/1782643/152330809-1e58f016-d928-4a0d-90e8-10ec8b2ed4fd.mp4

**Comment by kyeotic** [comment]
Gah, of course `useRoutes` works and `usePath` doesn't. I'm going to be playing whack-a-mole with this bug forever.

Thanks for the tip, I will try to get to this tomorrow

**Comment by dave-irvine** [comment]
I'm not 100% that useRoute is working completely either, as after the refresh the "go to Error" button doesn't work, it becomes impossible to navigate from Main to Error.
