### ISSUE TITLE
Compatibility with Typescript 3.x

### ISSUE THREAD

**Issue by roypearce** [kyeotic/raviger#120]
When I upgraded from v2.4.2 to v4.0.0 of raviger, I was greeted with a wall of errors. 

```
[tsl] ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts(16,18)
      TS1110: Type expected.

ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts
16:27-31
[tsl] ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts(16,28)
      TS1005: '}' expected.

ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts
16:31-32
[tsl] ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts(16,32)
      TS1128: Declaration or statement expected.

ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts
20:70-71
[tsl] ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts(20,71)
      TS1005: ';' expected.

ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts
20:71-72
[tsl] ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts(20,72)
      TS1005: ';' expected.

ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts
20:78-80
[tsl] ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts(20,79)
      TS1005: ';' expected.

ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts
20:81-82
[tsl] ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts(20,82)
      TS1109: Expression expected.

ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts
23:148-149
[tsl] ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts(23,149)
      TS1005: ';' expected.

ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts
23:149-150
[tsl] ERROR in /Users/roy/code/my-repo/node_modules/raviger/dist/router.d.ts(23,150)
      TS1005: ';' expected.
```

After looking into `ts-loader` (webpack), my `tsconfig.json` and other sources that could cause this issue without success, I noticed that `raviger` was using Typescript 4.x while my project was using Typescript 3.x.

**Upgrading to Typescript 4.x resolved these issues.**

**Comment by roypearce** [comment]
@kyeotic I don't think you need to do anything per-se, I just wanted there to be an issue so anybody else experiencing this will know how to resolve it.

**Comment by kyeotic** [comment]
I wonder if there is some way I am supposed to document this requirement. [Their docs ](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) don't mention one.

**Comment by roypearce** [comment]
Yea, I haven't seen anything that can denote typescript version dependency for a project. There is of course `peerDependencies` in `package.json` but that doesn't work since typescript is not really a pre-requisite to use raviger. It would also be counter-productive to compile raviger for v3 typescript as it's not a real burden in most cases for the user to update it to the latest, and is usually more advantageous for them to upgrade typescript anyway. 

You can add a line in the readme about it if you want, that's the first place I would look for an issue like this. The next place is here in Issues. It's just really annoying how not obvious the problem is, and it's not this project's fault, and I wouldn't want anyone exploring router options to be put off by this issue, because it is a pretty great project.
