### ISSUE TITLE
React 18 support: Unmet Peer Problem

### ISSUE THREAD

**Issue by rabilrbl** [kyeotic/raviger#121]
Issue with npm package manager.
![image](https://user-images.githubusercontent.com/63334479/163556222-5eee8b1f-6403-4c26-9112-9f9f08638996.png)

**Comment by kyeotic** [comment]
I have not had a chance to test raviger with React 18 yet. I am out of town this weekend, so my first opportunity will be on monday.

**Comment by kyeotic** [comment]
This has been released under 4.1.0
