### ISSUE TITLE
Nested Routing

### ISSUE THREAD

**Issue by orazdow** [kyeotic/raviger#123]
I am trying to get nested routing working, so it's more of a question than an issue. I did see that nested routing is mentioned, so I'm not sure what's wrong with how I am trying to implement it or if what I'm trying is possible?

What I'm trying to achieve is a view of components encapsulated in a routing component and it's styling, with this happening on a page routed to by the 'main' router at the entry point of the project. That sounds like what nested routing should do, but it seems that the nested router isn't handling routes and /nest/component routes navigate to a blank page.

I have this test as an example: [nest-route-test](https://github.com/orazdow/nest-route-test)

Thanks

**Comment by kyeotic** [comment]
I'd be happy to help you debug this if you can recreate the issue in a Codepen (or other similar online tool)

**Comment by orazdow** [comment]
No problem. Here it is on repl.it, you should be able to just hit "run":
[repl.it route test](https://replit.com/@orazdow/nest-route-test#src/nest.js)

**Comment by kyeotic** [comment]
I've never used repl.it, but holy wow is this a terrible UI. Why does the code only take up like, 20% of the entire window? There is more app-chrome than there is code. The only other option is to entire fullscreen... the footer is larger than the code... was this made as a prank?

Ok, terrible UI rant aside, this is not how nested routing work. Check out [this codesandbox](https://codesandbox.io/s/epic-elion-8urnt9?file=/src/nest.js). The key things to understand are

* The router needs to delegate subrouting using the `*` wildcard
* A `basePath` needs to be defined on `useRoutes`. This will be inherited by children `useRoutes` and `<Link/>`

**Comment by orazdow** [comment]
Ah I get it. It makes sense that the `*` is needed for the top-level router.
The codesandbox will help, and it has a good UI! Heh, although I had the same complaint about codepen and it's layout.
Thanks for your help.

**Comment by kyeotic** [comment]
> Ah I get it. It makes sense that the * is needed for the top-level router.
 To be clear, the `*` is needed for every level that wants to nest. In order to perform infinite nesting you can see that `<NestedRoutes/>` also uses a `*` for the next level of `/nest`
 
P.S.
In codepen you can drag-handle each code panel, or maximize individual panels (which minimizes the other two). You can also drag-handle the code-space vs the render-space. Codesandbox is a lot more powerful, but codepan can be quicker for small stuff.

**Comment by gigincg** [comment]
@kyeotic Thanks for the example for nested routing, but It doesn't seem to work, if the nested route has any path params in it. 

For instance the route "/a/:id/nest*" would require the nested router to be configured as 
```
useRoutes(routes, {basePath: basePath.replace(":id", pathParams.id)}
```

Is this intentional? Or am I doing it wrong somehow?
