### ISSUE TITLE
useHash: Cannot read properties of undefined (reading 'substring')

### ISSUE THREAD

**Issue by Prinzhorn** [kyeotic/raviger#126]
The argument here passed to the callback

https://github.com/kyeotic/raviger/blob/10d24e63b6c9f9329cc34df6365c639fca5cc529/src/location.ts#L78-L84

is an `Event` object from the `hashchange` here

https://github.com/kyeotic/raviger/blob/10d24e63b6c9f9329cc34df6365c639fca5cc529/src/location.ts#L87

It doesn't have a `hash` property.

Maybe consistently use `window.location.hash` and ignore the argument altogether.

**Comment by Prinzhorn** [comment]
Turns out that's how it _was_ :smile: 

https://github.com/kyeotic/raviger/commit/10d24e63b6c9f9329cc34df6365c639fca5cc529#diff-563a75de07924a14c7aa91020a763d60ff7682b796c2033d7e3ae9b1cdf704cdL47

**Comment by kyeotic** [comment]
Fix published under `4.1.2`

**Comment by Prinzhorn** [comment]
Thanks!

**Comment by kyeotic** [comment]
I don't understand how this one got around our tests. Does jsdom produce invalid `hashchange` events? I'm also surprised it took this long to find.

**Comment by Prinzhorn** [comment]
:shrug: this was my first time using the library and all I did was hit the browser back button, which triggered the exception. I was using `navigate('#foo')` + `useHash()`, no other features. So `navigate('#foo')` itself did _not_ cause the exception, only using the back button. I assume most people don't use the hash at all and that's why nobody noticed yet.

**Comment by kyeotic** [comment]
Oof, terrible first impression. Thank you for reporting the bug and not just moving on :D
