### ISSUE TITLE
Is nested path params supported?

### ISSUE THREAD

**Issue by coodoo** [kyeotic/raviger#128]
Trying to simulate the URL structure like github.com I've got these routes:

```
const routes = {
	'/': () => <Home />,
	'/user': () => <User />,
	'/user/:repo': () => <Repo />,
	'/user/:repo/issues': () => <Issues />,
	'/user/:repo/issues/:issue_id': () => <Issue />,
}
```
I expect `<Issue />` shall be invoked and shown on screen when I visit :

`http://localhost:5173/user/repo_foobar/issues/222`

and I could access `issue_id` (which should be `222`) like this:

`const [path, pairs] = usePathParams('/user/:repo/issues/:issue_id')`

But for some reasons `<Issue />` never showed on screen.

Did I miss something in the route config?

**Comment by coodoo** [comment]
After further tinkering around to find out the root cause is `issue_id`, changing it to `issueId` then everything worked like a charm. Now wondering why `underscore` or `dash` isn't supported as valid variable name in routes? 

PS. Please feel free to close this issue since the problem is solved now.

**Comment by kyeotic** [comment]
> Now wondering why underscore or dash isn't supported as valid variable name in routes?

[Not much is](https://github.com/kyeotic/raviger/blob/main/src/router.tsx#L203), its just this regex: `/:[a-zA-Z]+/`. I'm opening to changing these if you have a good reason, but if not then I should at least document this somewhere. I will leave this open in the meantime/

**Comment by coodoo** [comment]
One good reason being following characters are all legal and supported in a URL?

`; , / ? : @ & = + $ - _ . ! ~ * ' ( ) #`

[source](https://www.freecodecamp.org/news/url-encoded-characters-reference/)

**Comment by n33pm** [comment]
These are only legal and supported **URL** characters but there is no need do support these characters in the route matcher.

In my humble opinion keep it simple. each additional character ( route matcher ) can lead to unexpected problems.

**Comment by coodoo** [comment]
Actually I agree with everyone here on keeping it simple is good, also not supporting `_` is really not that of a big deal, just make sure to note that in the doc so future users know ahead of time! 🙌

**Comment by kyeotic** [comment]
I've [changed my mind on this](https://github.com/kyeotic/raviger/issues/129#issuecomment-1684061354) and plan to add support for more URL characters.
