### ISSUE TITLE
How to create protected route 

### ISSUE THREAD

**Issue by adventuretocode** [kyeotic/raviger#131]
Hi there I have read the https://kyeotic.github.io/raviger/ Document but i can't find the anywhere about the protected route.

**Comment by kyeotic** [comment]
What is a protected route?

**Comment by adventuretocode** [comment]
@kyeotic   in React Protected route based on user auth the route Access only this like same as user role based access.

**Comment by kyeotic** [comment]
Do you have a link to the docs that explain that as a _React_ component?_ I think you are confusing React with _React Router_, a different navigation library than raviger.

raviger does not provide any authentication related components, but they would be easy to implement. They could look something like this

```js

function App () {
  const { isAuthenticated } = useCustomAuthHookFromYourAppOrChosenLibrary()
  const route = useRoutes(routes)
  
  return (
    <div>
      { isAuthenticated ? route : <AuthOrLoginGuard/>
    </div>
  )
}


```

**Comment by adventuretocode** [comment]
Thanks so much @kyeotic
