### ISSUE TITLE
Class on active links

### ISSUE THREAD

**Issue by Saghen** [kyeotic/raviger#19]
If the `Link` component has the path `/login` and the user is currently navigated to `/login`, the Link component could have a class labelling it as an active link as used in the vue-router: https://router.vuejs.org/api/#linkactiveclass

The API could follow after react-router: https://reacttraining.com/react-router/web/api/NavLink

Additionally, a class for exact and non-exact matching would be appreciated. For example, if the user is at `/user/login` the `/user` Link could have an `link-active` class while the `/user/login` Link could have an `link-active-exact` class.

**Comment by kyeotic** [comment]
@Saghen  published under `0.5.7`
