### ISSUE TITLE
useRedirect hook

### ISSUE THREAD

**Issue by sdirosa** [kyeotic/raviger#2]
It would be nice to be able to setup redirects via a `useRedirect` hook or similar mechanism.

I expect the router to navigate the user to the target path (preserving the queryString if present) and replacing the navigation history with the destination path.

**Basic example**

```jsx harmony
import {useRoutes, useRedirect} from 'raviger';

const routes = {
  '/dashboard': () => 'Dashboard'
};

const MyApp = () => {
  useRedirect('/', '/dashboard);
  return useRoutes(routes) || 'oops';
}
```

I'd expect the user to end up in the /dashboard page when hitting the root of the App and having only /dashboard in its History. 

**Extra**
Could be interesting to think about merging queryParameters defined in the `useRedirect` hook configuration with the ones provided in a Link.
For example I could setup a redirect such as 
```jsx harmony
  useRedirect('/', '/dashboard?redirected=1');
```
Or 
```jsx harmony
  useRedirect('/', '/dashboard', {redirected: 1});
```

And then later in a hypothetical SomePage component make a Link to go back to the Dashboard
```
  <Link href='/?from='some-page''>Go back</Link>
```

In this case I'd expect the queryParameters to contain both `redirected` and `from`

But this is already quite advanced, I'd be very happy already with the Basic functionality :)

**Comment by kyeotic** [comment]
I'm not sure preserving the querystring makes sense here. I'd rather leave it up to the redirector to decide if that should happen. It doesn't seem like it should be the default behavior for a redirect operation. You could do it like this though (after #3 gets merged)

```javascript
const MyApp = () => {
  useRedirect('/', '/dashboard', useQueryParams());
  return useRoutes(routes) || 'oops';
}

```

**Comment by sdirosa** [comment]
> I'm not sure preserving the querystring makes sense here.
...
>You could do it like this though (after #3 gets merged)
> ```js
> const MyApp = () => {
>   useRedirect('/', '/dashboard', useQueryParams());
>   return useRoutes(routes) || 'oops';
> }
> ```

100% agreed. 
This is actually **a lot** nicer than what I had in mind, and simpler too.
I'll test this out tomorrow, together with the new navigate (https://github.com/kyeotic/raviger/pull/3)

Thanks a bunch for the quick changes :open_hands:

**Comment by kyeotic** [comment]
@sdirosa added in `0.3.4`. Keep those feature requests coming :)

**Comment by sdirosa** [comment]
@kyeotic Sweet! Just tested the ueRedirect and it works like a charm.

My router setup now looks something like:

```js
const LazyOverview = React.lazy(() => import('../Overview'));
const LazyPage1 = React.lazy(() => import('../Page1'));
const LazyPage2 = React.lazy(() => import('../Page2'));
const LazyLogin = React.lazy(() => import('../Login'));
const LazyLoginCallback = React.lazy(() => import('../LoginCallback'));
const LazyGoodbye = React.lazy(() => import('../Goodbye'));
const LazyLogout = React.lazy(() => import('../Logout'));
const LazyNotFound = React.lazy(() => import('../NotFound'));

const publicRoutes = {
  '/login': () => <LazyLogin />,
  '/login-callback': () => <LazyLoginCallback />,
  '/goodbye': () => <LazyGoodbye />
};

const privateRoutes = {
  '/overview': () => <LazyOverview />,
  '/logout': () => <LazyLogout />,
  '/page1': () => <LazyPage1 />,
  '/page2': () => <LazyPage2 />
};

const Router = () => {
  const { isLoggedIn } = React.useContext(AuthenticationContext);
  useRedirect('/', isLoggedIn ? '/overview' : '/login');
  return useRoutes(isLoggedIn ? privateRoutes : publicRoutes) || <LazyNotFound />;
};

export default Router;


```



Something odd I stumbled upon. I had to checkout and recompile the module myself, for some reason if I just `yarn install raviger` I end up with a `dist/lib.js` but no main and module as before. 

I'm not sure if this is intended, bit in that case all of my imports stopped working (now that I think of it maybe they would have worked anyway adding a ~ in front of the package name, but didn't try that)

Going to play around with the new navigate ;)

**Comment by sdirosa** [comment]
@kyeotic 
The new `navigate` with params / URLSearchParams works really well too. 

Thanks man, this really simplifies things a lot!


As a follow up about the npm package issue above; our CI also died up on the package not being found from 0.3.3 and up. Just tested that reverting to 0.3.2 it works fine (without the latest awesomeness of course)

**Comment by kyeotic** [comment]
@sdirosa Is your CI using an internal artifactory? Ours does this, and it only reindexes public npm every hour.

The redirect strategy is nice. You can clean it up a little with a custom hook.

```javascript
// module 1
export function isLoggedIn () {
  return React.useContext(AuthenticationContext)
}

// module 2
import { isLoggedIn } from './module1'

...
const Router = () => {
  const isLoggedIn = isLoggedIn();
  useRedirect('/', isLoggedIn ? '/overview' : '/login');
  return useRoutes(isLoggedIn ? privateRoutes : publicRoutes) || <LazyNotFound />;
};
```

I like the double route set strategy. Why is the redirect only setup for `/overview` though?

**Comment by kyeotic** [comment]
About the recompile thing, this is my first library using rollup so there is a good chance I didnt get the rollup.config right. Its _supposed_ to offer the compiled version as main, and the uncompiled version for bundlers that know how to handle it. Are you using webpack or rollup for bundling/building? If webpack, are you transpiling `node_modules`?

**Comment by kyeotic** [comment]
@sdirosa I figured out the compile thing, I had published without buidling, so the file it needed wasn't there. It has been fixed in latest

**Comment by sdirosa** [comment]
> @sdirosa I figured out the compile thing, I had published without buidling, so the file it needed wasn't there. It has been fixed in latest

I use vanilla CRA for this project. We have a very simple Jenkins/Docker pipeline setup. I'm trying to keep dependencies and stack as plain as possible while I experiment with stuff.

Our Jenkins doesn't do much more than running yarn install + yarn build and a bunch of tasks like linting, unit tests, integration tests, etc.

Anyway, that fixed it up!
I just upgrade to 0.3.6 and it's all working as expected now :+1:

**Comment by sdirosa** [comment]
> @sdirosa Is your CI using an internal artifactory? Ours does this, and it only reindexes public npm every hour.
> 
> The redirect strategy is nice. You can clean it up a little with a custom hook.
> 
> ```js
> // module 1
> export function isLoggedIn () {
>   return React.useContext(AuthenticationContext)
> }
> 
> // module 2
> import { isLoggedIn } from './module1'

Interesting idea! I've never thought of using imports to destructure contexts. I'm going to play around with this. Thanks for the tip! 

> I like the double route set strategy. Why is the redirect only setup for `/overview` though?

Our product is available only to authenticated users and doesn't really have a welcome page or anything to greet the user (yet). 

We just send them to one of our overview after validating their session by redirecting to '/'. 

Anonymous users can basically access only the login page, which sends them to a 3rd party authentication layer.

**Comment by kyeotic** [comment]
> Anonymous users can basically access only the login page, which sends them to a 3rd party authentication layer.

If thats the case, you can skip the redirect and just return the `<Login>` component when they aren't logged in. If the whole app is authenticated you can put this at the top level, above the router.

**Comment by sdirosa** [comment]
> > Anonymous users can basically access only the login page, which sends them to a 3rd party authentication layer.
> 
> If thats the case, you can skip the redirect and just return the `<Login>` component when they aren't logged in. If the whole app is authenticated you can put this at the top level, above the router.

Indeed. For login it would work fine. For other pages not so much; it would leave the url out of sync or create multiple routes for the same component.

Eg: Overview would render both under `/` and `/overview`. useRedirect fixes the problem entirely :)
