### ISSUE TITLE
useQueryParams hook returns stale values when going back in history

### ISSUE THREAD

**Issue by yenoiwesa** [kyeotic/raviger#30]
Hello, it's me again 👋 

So it seems that the latest changes introduced for `useLocationChange` have caused a problem with other hooks using it (not exactly sure why though).

When using `useQueryParams`, the URL param values returned when going back in history (web browser back button) do not reflect the current window location parameters, they are behind (stale).

I reverted to `raviger` `0.5.9` and the problem disappeared.

Would you have any idea what could cause that?
If that's too vague I can work on building a reproduction somewhere, let me know.

**Comment by kyeotic** [comment]
Well both functions were affected by the refactor, but [not in an obviously wrong way](https://github.com/kyeotic/raviger/compare/v0.5.9..v1.0.0-rc.2).

I'll see what I can figure out.

**Comment by kyeotic** [comment]
Yikes. So, I cannot reproduce this with a unit test. Jest doesn't appear to implementing `history.back()`. However, I can reproduce it with the `/example` harness, and I can fix it with... a performance optimization?

Not totally sure what's going on yet, but I added a memoize-callback and the issue went away. I'm going to publish it on rc3, and leave this issue open while I try to find a way to get a regression test added.

**Comment by kyeotic** [comment]
Try `raviger@rc` or `raviger@1.0.0-rc.3` and let me know

**Comment by yenoiwesa** [comment]
Just tested with `raviger@1.0.0-rc.3` and I confirm it's working fine!

**Comment by kyeotic** [comment]
If anyone knows how [this change](https://github.com/kyeotic/raviger/compare/v1.0.0-rc.2..v1.0.0-rc.3#diff-e9fddabda7ec9bbdc24268e36246deb4L19) could impact this, or how to recreate the failure in a [unit test](https://github.com/kyeotic/raviger/compare/v1.0.0-rc.2..v1.0.0-rc.3#diff-c9c33e0b9af36e6d724ae27af91559fbR32) your input would be very appreciated

**Comment by yenoiwesa** [comment]
After more than an hour trying to debug the issue (and it's now 11.30pm here in Sydney hehe) I think I have found the reason for the bug.

`useRoutes` will always be used in a parent component of any component that themselves use `useQueryParams` or `usePath`.

`useRoutes` uses `useLocationChange` [here](https://github.com/kyeotic/raviger/blob/7267758558f8566ecef2f1bb79b67b4174c0c10d/src/router.js#L24).

If you comment out the `useLocationChange` usage in `useRoutes`, the bug disappears.

This is because whenever the `popstate` event is triggered, it will be fired on the event listeners in the order they were registered, hence the component using `useRoutes` will receive it first.
That component will re-render, causing the children component using the other two hooks to re-render too. This is happening synchronously, before the children hooks get a chance to receive their own `popstate` event.

But since the `useQueryParams` hook does not keep a stable reference to the callback it passes to `useLocationChange`, the render loop being called on that component will cause a new callback to be passed, and the `useEffect` to trigger its clean up effect, which will unbind the `popstate` listener.

So when the event loop has finished the render and goes back to firing the remaining `popstate` event to the other listeners, the `useQueryParams` listener has already been unbound, and thus will not be triggered.

Now, what I am not clear about is why going forward in history is fine.... 
And I'll rather go to bed than investigate that!

**Comment by kyeotic** [comment]
That is some excellent debugging work, and I'm inclined to believe that is the cause. The trouble is that this is a bug that could bite other users who fail to provide a stable callback to `useLocationChange`. I'll do some research, perhaps there is a way to notify users when they do so. Or, even better, mitigate the problem when they do.

**Comment by kyeotic** [comment]
@yenoiwesa I believe I have a good solution, see #31 for details. This should protect users from this bug

**Comment by kyeotic** [comment]
Ive published under `1.0.0-rc.4`
