### ISSUE TITLE
Early issue with nested `useRoutes`

### ISSUE THREAD

**Issue by micmcg** [kyeotic/raviger#34]
Sorry for the vague issue but I just thought I would give you a heads up while investigating. 
Since upgrading to `1.0.0-rc.3` (Also tried `rc6`) we have been having issues with previously working nested `useRoutes`. 

The basic structure of our app is as follow

An "App" with `useRoutes` that either maps to a list page or a view entity page
`basePath` is `foo/bar/entities`
Routes are similar to the following
```
const routes = {
    '/': () => <ListPage />,
    '/:id/*': ({ id }) => (
        <ViewPage id={id} />
    ),
}
```

A view entity page with `useRoutes` that maps to 3 tabs within the page,
`basePath` is `foo/bar/entities/<id>` where `id` is a numeric id. 
Routes are similar to the following
```
const routes = {
    "/tab1": () => <Component1 />,
    "/tab2": () => <Component2 />,
    "/tab3": () => <Component3 />
}
```

Previously (0.5.8) we were using `usePath` within one of the tabs (so 2 `useRoutes` deep) with no problems, it would always return the path we expected (`/tab2`) 
Now however, if you land on tab2 (i.e. start a new browser tab at the  url `foo/bar/entities/1/tab2`) `usePath` will return the correct value (`/tab2`) 
But as soon as you navigate to a different tab `usePath` (called within the tab) starts returning  `/1/<tabNo>`. The `basepath` in the context is correct (has the `id` at the end of the path), but it's like it calculated the `path` based on the `basePath` of the router one level higher. 

```
context = { path: '/1/tab2', basePath: 'foo/bar/entities/1' }
```

I'll keep adding detail to this issue as I investigate, but I thought it might be possible you have an idea what's going on. 

Thanks

**Comment by kyeotic** [comment]
I hate to push this back, but I'm having some trouble understanding what your setup is, exactly. Any chance you can create a minimal? Here is a [codesandbox](https://codesandbox.io/s/silly-lewin-evthb) setup with the example harness to get you started.

I will try to reproduce this bug.

**Comment by micmcg** [comment]
Totally understandable. Unfortunately I am heading out of the office for 5 days, but if I can't give you more information when I get back I will at least give you a minimal reproduction case.

**Comment by kyeotic** [comment]
Actually I think I see the issue in that codesandbox! If you go to a deep route the `basePath` is in the `path`, but not on initial load. That's definitely a bug. I will get this fixed, but possibly not until tomorrow.

**Comment by kyeotic** [comment]
@micmcg I've got a fixed, will be publishing under `1.0.0-rc.7`

**Comment by kyeotic** [comment]
I'm headed to bed, hope you enjoy your trip 😄

**Comment by yenoiwesa** [comment]
Bugs happen but great support from maintainers is rare! We all appreciate **very** much the effort you put in making sure that your library is top notch. Kudos to you @kyeotic!

**Comment by micmcg** [comment]
Thank you @kyeotic, I can confirm this fixed the issue for us 👍

**Comment by kyeotic** [comment]
@micmcg glad to hear it. In case you missed it, #27 1.0 is out

**Comment by micmcg** [comment]
> @micmcg glad to hear it. In case you missed it, #27 1.0 is out

Yep I saw that, it's what we are running now. 
Congratulations @kyeotic on reaching this milestone 🎉
