### ISSUE TITLE
Allow passing ref to the Link anchor.

### ISSUE THREAD

**Issue by carlababa** [kyeotic/raviger#36]
I'm currently using the raviger `Link` for a list of links and I'm trying to use keyboard navigation to navigate through them.
To move the focus through the links I would need to set a ref on the anchor elements, this is currently not possible.
This would be easily achieved by adding `forwardRef` on the `Link` component and then pass the ref to the anchor element.
I would really appreciate if this could be implemented. :)

**Comment by kyeotic** [comment]
I’d be happy to add that, but I am interested in understanding this a
little bit more. Does tabbing through the kinks not work for you currently?
Or are you trying to create programmatic focus via other means, like a
shortcut key?

**Comment by kyeotic** [comment]
I haven't used Ref forwarding before, though it [sounds simple enough](https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components). However, [this note](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers) is giving me pause. Like [this SO question](https://stackoverflow.com/questions/53447432/is-adding-forwardref-to-a-function-component-a-breaking-change) I don't understand _how_ this could be a breaking change for a functional component. Without that understanding I don't know what tests I need to cover this change.

**Comment by carlababa** [comment]
Hey @kyeotic, thanks for looking into this.
Indeed I'm trying to programmatically focus via shortcut key.
I do understand your concern with adding `forwardRef` since it will be a breaking change and require you to release a major version for it.
The non-standard prop might work as well for us.

**Comment by micmcg** [comment]
`<Link linkRef={ref]>` sounds fine to me

**Comment by kyeotic** [comment]
published under `1.1.0`
