### ISSUE TITLE
useQueryParams setter does not preserve hash value

### ISSUE THREAD

**Issue by yenoiwesa** [kyeotic/raviger#39]
Hello @kyeotic 👋 

We found an issue with `raviger` not preserving the hash part of the URL when using the `useQueryParams` hook to set the query parameters with `replace: true`.

I have created a reproduction here: [Code Sandbox](https://codesandbox.io/s/confident-yonath-rplmz)

Let me know if you need more details :-)

**Comment by kyeotic** [comment]
Thank you for the repro. I would expect this behavior when `replace: true`, but not when `replace: false`. It appears to happen with both. Interestingly the `replace: false` doesn't seem to merge query string values in code sandbox, but it does in my app and in the dev-example app.

I'm going to add some tests around this, and stop `replace: false` from clobbering the hash

**Comment by kyeotic** [comment]
Oh man, when I went to update the docs I realized I had documented the function backwards. `replace:true` doesn't merge the querystring, `replace: false` does (as it clearly should, based on the name).

**Comment by kyeotic** [comment]
Every single time I use a boolean as an optional second param I regret not using an options object.

**Comment by kyeotic** [comment]
fix published under `1.1.1`

**Comment by yenoiwesa** [comment]
> Oh man, when I went to update the docs I realized I had documented the function backwards. `replace:true` doesn't merge the querystring, `replace: false` does (as it clearly should, based on the name).

Ah right! Because I was following the documentation on this and thought "huh wait..?".

Thanks for the fix!
