### ISSUE TITLE
Cannot remove URL parameters using useQueryParams

### ISSUE THREAD

**Issue by yenoiwesa** [kyeotic/raviger#42]
Hey again,

This one is probably a feature request, but currently it is not possible to remove a URL parameter using the `useQueryParams` setter function.

For instance doing `setQueryParams({ foo: null });` sets the value of `foo` to the string `"null"`.
I would have expected `undefined` or `null` to actually remove the parameter from the URL.

Otherwise, the only current solution is to use `replace: true`, which forces the component to retrieve and potentially alter the parameters it should not know about.

Here is an example: [Code Sandbox](https://codesandbox.io/s/crazy-architecture-7gpnl)

**Comment by kyeotic** [comment]
nah, this is a bug

**Comment by kyeotic** [comment]
setting a query to `null` will remove it from the querystring after #43 merges

**Comment by kyeotic** [comment]
published under `raviger@1.1.2`

**Comment by yenoiwesa** [comment]
Awesome! Thanks.
