### ISSUE TITLE
Bug when using a percent (%) symbol query parameter value

### ISSUE THREAD

**Issue by lumberjacklv** [kyeotic/raviger#44]
When a percent (%) symbol is used as part of the query parameter it will blow up on decodeURIComponent because URLSearchParams returns the value already decoded.
This was tested on:
- Chrome 68.0.3440.84 on Mac
- Microsoft Edge 80.0.361.33 on Mac
- Safari 13.0.2 (15608.2.30.1.1)

The current workaround is to encode the URI before sending to setQueryParams

**Comment by kyeotic** [comment]
Is the error happening when you make a call to `setQueryParams`?
