### ISSUE TITLE
Navigating to a page that uses useQueryParams causes an extra history entry

### ISSUE THREAD

**Issue by lumberjacklv** [kyeotic/raviger#46]
When navigating to page that uses `useQueryParams` the history is updated twice causing the user to have to use the back button twice to get back to the previous page.

**Comment by kyeotic** [comment]
I'm not seeing this behavior. I've tried using the `/example` in the repo, as well as with a [codesandbox](https://codesandbox.io/s/practical-night-97znj) and the back button behaves normally. Can you provide a reproduction with codesandbox?

**Comment by lumberjacklv** [comment]
@kyeotic There is no issue. Thanks for the example because it made me realize where the real issue was.

**Comment by kyeotic** [comment]
If you don't mind sharing, I'm interested in the cause. Perhaps I can add a warning to the docs so that future users can avoid the pitfall.

**Comment by lumberjacklv** [comment]
I was using setQueryParam in a useEffect, it was called on the first page load. What I did to stop it from calling setQueryParam when the params haven't actually changed.

**Comment by kyeotic** [comment]
@lumberjacklv Thank you, I'm going to add a warning tot he `set` docs :)
