### ISSUE TITLE
Problems with navigation and nested routes

### ISSUE THREAD

**Issue by macku** [kyeotic/raviger#50]
Hi, I've found some strange problems with navigation when you are using nested routes with params. I'm testing with the latest version 1.4.

## How to reproduce?
Here is the link to the reproduction code:
https://stackblitz.com/edit/react-raviger-test?file=index.js

Press on the links in the bottom part in that order to:
1. nested with a param About (the route is loaded)
2. nested with a param Test (the route is **not** loaded)
3. root (the route is loaded)
4. nested with a param Test (the route is loaded)
5. root (the route is loaded)
6. nested with a param Test (the route is loaded)
7. nested with a param About (the route is **not** loaded)

![raviger-bug](https://user-images.githubusercontent.com/227305/80435097-f6cf9b80-893e-11ea-94fc-3f89056979fd.gif)

## Possible cause
I've checked many things, and I think the `useLocationChange` hook is the main suspect. It looks like [the if condition with `inheritBasePath` option](https://github.com/kyeotic/raviger/blob/1e7992cf08fafd6ac7429197a2b08bdbd450d9ad/src/path.js#L51) is causing the problem. I haven't found any other place where this option is used internally.

I was trying to debug the code with breakpoints in browser devtools. After setting the value of `basePath` to what is provided with `options` the issue is gone:
<img width="633" alt="inheritBasePath-hack" src="https://user-images.githubusercontent.com/227305/80434568-7197b700-893d-11ea-8297-e32bb0493214.png">
![raviger-fixed](https://user-images.githubusercontent.com/227305/80434884-5d07ee80-893e-11ea-8509-2c3a243c6027.gif)

Do you reckon we could somehow fix this behaviour? Maybe we just need to remove the `inheritBasePath` condition 😄 or force the `false` value when using hook internally from the `useRoutes` hook?

**Comment by kyeotic** [comment]
This is definitely a bug, but the bug seems to be in `usePath` not providing `inheritBasePath: false` when it has a `basePath` itself to pass in. The behavior of `inheritBasePath` matches the docs, and makes sense to me. I'll have a PR and a beta up for you shortly.

**Comment by kyeotic** [comment]
@macku I released a beta which hopefully addresses this, see #51 for details

**Comment by macku** [comment]
Awesome! Let me take a look and check that

**Comment by macku** [comment]
I can confirm that this change works:
https://stackblitz.com/edit/react-raviger-test?file=index.js

**Comment by kyeotic** [comment]
Ok cool, I will release that as a patch tomorrow morning (Pacific)

**Comment by kyeotic** [comment]
fix publishes under ` 1.4.1 `

Thanks for all the research on this @macku, you made it a breeze to fix :)
