### ISSUE TITLE
Base path matcher regexp is not case insensitive

### ISSUE THREAD

**Issue by yenoiwesa** [kyeotic/raviger#58]
Hi @kyeotic 👋 

We had a bug ticket in production where our silly users decided to access our single page app by changing some part of the base path URL to be lowercase (silly I know).

Unfortunately that is something that we used to support before so we had to write a temporary fix on our side.

The issue is here: https://github.com/kyeotic/raviger/blob/ea4a3f5a345268bd56af9f0716b7e49bc936d32a/src/path.js#L78-L80

If the line was changed to make the RegExp case insensitive, our problem would be solved:
```js
return new RegExp('^' + basePath, 'i')
```

Would it be possible to either make it case insensitive, or have an option to do so?

Thanks in advance!

**Comment by kyeotic** [comment]
I totally understand, this is absolutely something we should offer. Since you have a PR up I will track the discussion there.

**Comment by kyeotic** [comment]
published under [1.4.4](https://github.com/kyeotic/raviger/releases/tag/v1.4.4)

**Comment by yenoiwesa** [comment]
Thanks @kyeotic, I upgraded to `1.4.4` and it works perfectly.

Cheers 🥳
