### ISSUE TITLE
Possible race condition with `usePath`

### ISSUE THREAD

**Issue by fpyir** [kyeotic/raviger#64]
Hello!

While working on a project @ my day job I came across what looks to be a race condition with `usePath` and `navigate`. 

I've created a code sandbox that reliably replicates the issue:
https://codesandbox.io/s/ecstatic-silence-16zr4

**Steps to reproduce**
1. Navigate to `/about`.
2. Reload the page so that we 'start' on `/about`.
3. Open up your browser console so you can see the logs.
3. Press 1 on the keyboard.

*What should happen:* Navigates to home page, one console log from `Home` saying `home path: /`
*What actually happens:* Navigates to home page, but we get **two** console logs. One from the `/about` component, and one from the `/` root component.

From what I can gather, using `navigate` seems to update the value returned by `usePath` *before* the navigation is complete - thus giving components we are navigating away from the chance to run code based off the changed path value. For example, in a `useEffect`: 
```
  useEffect(() => {
    setTabUrl(path);
  }, [path, setTabUrl]);
```

**Comment by kyeotic** [comment]
Thanks for the report and reproduction @fpyir, that will make this much easier to fix.

**Comment by kyeotic** [comment]
@fpyir I haven't forgotten about this, its just proving a little harder than normal to create a unit test for.

**Comment by fpyir** [comment]
Yes it's a tricky bug! Thank you for getting right on it.

**Comment by kyeotic** [comment]
I've tried several routes and I cannot reproduce this in a unit test, which makes fixing it difficult and unreliable (it might regress).

What's frustrating is that the unit test components behave as they are expected to
```
   console.log test/path.spec.js:145
      harness update [Function: About]
    console.log test/path.spec.js:134
      about /about
    console.log src/path.js:66
      changing path /
    console.log src/path.js:66
      changing path /
    console.log test/path.spec.js:145
      harness update [Function: Home]
    console.log test/path.spec.js:127
      home /
```

Here is the latest test (which passes)
```javascript
test('usePath is not called when unmounting', async () => {
    const homeFn = jest.fn()
    function Home() {
      const path = usePath()
      console.log('home', path)
      homeFn(path)
      return <span data-testid="path">{path}</span>
    }
    const aboutFn = jest.fn()
    function About() {
      const path = usePath()
      console.log('about', path)
      aboutFn(path)
      return <span data-testid="path">{path}</span>
    }

    const routes = {
      '/': () => <Home />,
      '/about': () => <About />
    }
    function Harness({ routes, basePath }) {
      const route = useRoutes(routes, { basePath })
      console.log('harness update', route.props.children.props.children.type)
      return route
    }

    act(() => navigate('/about'))
    const { getByTestId } = render(<Harness routes={routes} />)
    expect(getByTestId('path')).toHaveTextContent('/about')
    expect(aboutFn).toHaveBeenCalledTimes(1)

    aboutFn.mockClear()

    act(() => navigate('/'))
    expect(getByTestId('path')).toHaveTextContent('/')
    expect(homeFn).toHaveBeenCalledTimes(1)
    expect(aboutFn).toHaveBeenCalledTimes(0)
  })
```

In other words: I'm still working on this.

**Comment by kyeotic** [comment]
It seems like the issue go away when the navigation [isn't triggered by a keyboard event](https://codesandbox.io/s/proud-thunder-274xv?file=/src/App.js)

**Comment by kyeotic** [comment]
@fpyir  It appears you have stumbled upon a deep architectural bug. For reasons I don't totally understand this bug only occurs when `navigate` is part of a timeout. When triggered synchronously by a component it behaves as expected. I will be tracking potential solutions in PR #65

**Comment by kyeotic** [comment]
@fpyir Im still working on this. I think I have part of a solution, but the expected behavior here is a bit loosely defined.

You're running a test with a `console.log`, which is a side effect, inside the render loop of of a component. Typically the advise is not to do things like this because react may run render several times while sorting out what to batch, which is why the `useEffect` hook behaves the way it does.

Would you consider it a solution if the child route that looked liked this
```javascript
const About = () => {
  const path = usePath();
  const [, setTabUrl] = useTabUrl();
  
  useEffect(() => {
    console.log(`about path: ${path}`);
    setTabUrl(path);
  }, [path, setTabUrl]);

  return (
    <div>
      <p>About: {path} </p>
    </div>
  );
};
```

Only ever logged to the console with `about path: /about`, even if this happened once while the page was changing? This _seems_ to me like the correct behavior, but I want to get some agreement before moving forward.

**Comment by fpyir** [comment]
Yeah that sounds perfectly reasonable to me - in our products code we obviously don't have any side effects that aren't in a `useEffect`, `useCallBack`, `useMemo` ect.

**Comment by kyeotic** [comment]
@fpyir 

I've released a beta under `1.4.6-0`. Install with

```bash
npm i raviger@1.4.6-0
# or
npm i raviger@beta
```

This reworks the internals of `useRoutes` so that it tracks the path differently. Unit testing shows that code in `useEffect` hooks do not receive the wrong path. Im releasing this as a beta because none of the apps I manage have encountered this bug and I am unsure of the total impact of this change.

I will leave it as a beta for two weeks, or until you confirm it fixes your issue without introducing any other bugs. Whichever comes first.

**Comment by yenoiwesa** [comment]
@kyeotic I just performed a test with the beta version and that fixed the (specific) issue we were facing without any change in our code base! 🥳 

I'll send a pull request for the library upgrade and we will dog food it for a while to make sure there are no routing regressions. We'll let you know!

Thanks again!

**Comment by n33pm** [comment]
Hey!

Is this one the same problem? 🤔
https://codesandbox.io/s/cranky-grass-t7f2f
if you switch `usePath` and `useRedirect` it works!

**Comment by kyeotic** [comment]
@n33pm I forgot to release this on main, I will do that now

**Comment by yenoiwesa** [comment]
Sorry @kyeotic we forgot to come back to you regarding this issue.
Our dogfooding hasn't found any issues with the beta release and we're now moving to the final release of raviger.

Thanks heaps for your support!

**Comment by yenoiwesa** [comment]
For future references, this issue relates to our internal ticket BBSDEV-22667.
