### ISSUE TITLE
basePath not working on top level component

### ISSUE THREAD

**Issue by martinsura** [kyeotic/raviger#66]
Hello,

First - thanks for this nice library. I have s one struggle. In hookrouter you can use setPath function on start application (https://github.com/Paratron/hookrouter/blob/master/src-docs/pages/en/05_serverside-rendering.md#setting-the-path)

I have react application which is serving in subofolder - for example (www.sampleapp.com/subfolder/sampleapp.

In top level component i have define routes:

``` 
const route = useRoutes(AppRoutes, { basePath: "sampleapp" });
```

But this is not working.

Is there any workaround, how i use basePath(setPath) for this usecase?

Thanks

**Comment by kyeotic** [comment]
If you are trying to host at `/subfolder/sampleapp` then you would need 
```js
const route = useRoutes(AppRoutes, { basePath: "subfolder/sampleapp" });
```

If you are having an issue try reproducing it in a [codesandbox](https://codesandbox.io/s/practical-night-97znj). That will help me diagnose your issue

**Comment by martinsura** [comment]
Well, this is not easy to reproduce in codesandbox because its server configuration related.

But i can try 
```  
 let route = useRoutes(AppRoutes, { basePath: "subfolder/sampleapp" }); 
```
on top component and nothing changed.
Btw in this sandbox
https://codesandbox.io/s/jovial-mestorf-x0gpr 
after basePath is set, application still working (expected not work - ``` https://x0gpr.csb.app/**test**/about```)

**Comment by kyeotic** [comment]
What do you mean its server configuration related? What exactly is happening that you think is incorrect behavior?

**Comment by martinsura** [comment]
Well
https://codesandbox.io/s/jovial-mestorf-x0gpr

In this sandbox, after click about page expected the url will be ```https://x0gpr.csb.app/test/about```
When clicked to filter the url will be ```https://x0gpr.csb.app/filter`` and so on

**Comment by kyeotic** [comment]
This is because the `<Link>`s in the app render are outside of the `useRoutes` result, so they can't inherit the `basePath` from it. The `basePath` is only provided to components rendered by `useRoutes`. Does that make sense?

You can provide the `basePath` to the `<Link>`, or you can create a wrapped version of the `<Link>` that has its own `basePath` defined.
```javascript
const AppLink = (props) => <Link {...props} basePath='test' />
```

 Check out [this example](https://codesandbox.io/s/naughty-goldwasser-91s7g?file=/src/App.js)

**Comment by martinsura** [comment]
Nice, this is exactly my use case and it works!

Thanks for the help.
