### ISSUE TITLE
matchTrailingSlash doesn't work with "/"

### ISSUE THREAD

**Issue by yunyu** [kyeotic/raviger#69]
Just a nit – when matchTrailingSlash is enabled, the "/" route needs to be renamed to "" for matching to work. This is a bit unexpected!

**Comment by kyeotic** [comment]
I need to think about this a bit. A repro would help

**Comment by yunyu** [comment]
@kyeotic If it helps, here's a repro: https://codesandbox.io/s/misty-paper-g03hs?file=/src/App.js

**Comment by kyeotic** [comment]
You're right, this behavior is unexpected. The existing logic is handling the _end_ of the URL, but in the case where its just `/` the end is also the beginning. This is worth special casing.

**Comment by kyeotic** [comment]
published under `1.5.1`
