### ISSUE TITLE
Feature: <Redirect /> doesn't support query params

### ISSUE THREAD

**Issue by yunyu** [kyeotic/raviger#70]
`navigate` currently has support for queryparams/URLSearchParams, but the Redirect component does not.

**Comment by kyeotic** [comment]
Good point

**Comment by kyeotic** [comment]
@yunyu Im still thinking about #69, but if that PR looks good I can publish it

**Comment by yunyu** [comment]
@kyeotic I looked at the tests, the behavior is definitely what people would expect. Thanks for the really quick turnaround and great project!

**Comment by kyeotic** [comment]
this has been published under `raviger 1.5.0`
