### ISSUE TITLE
convert to typescript

### ISSUE THREAD

**Issue by kyeotic** [kyeotic/raviger#83]
V3 should be written in typescript

**Comment by n33pm** [comment]
#88 tried my best 😜

**Comment by n33pm** [comment]
how do we continue here @kyeotic  ?

**Comment by kyeotic** [comment]
Honestly I forgot about this. I need to review it and merge the changes since you did the conversion in. It's very difficult to compare since the diff shows the files as deleted, not changed.

**Comment by n33pm** [comment]
I created an additional branch (https://github.com/n33pm/raviger/tree/feat/typescript) to separate rename and changes. 😅

https://github.com/n33pm/raviger/compare/63064ae792a85bcb2c4e72bf4e1c1cc4d3c3e617...n33pm:4a167d8cffd9ef8c58d43f908604d17142ce079e

**Comment by kyeotic** [comment]
That's incredibly helpful, not sure how you put that together. I've merged your PR into my local `typescript` branch to continue working on it.

**Comment by kyeotic** [comment]
@n33pm ive synced a lot of the changes (maybe all?) from updates since this branched. The major hold-up at this point is that the bundle size has increased from 2.6k to 5.7k, more than double. I need to figure out whats taking up the extra space before merging.

you can check out the current `typescript` branch
