### ISSUE TITLE
French localised documentation pages mixed with English

### ISSUE THREAD

**Issue by yenoiwesa** [kyeotic/raviger#90]
Hey @kyeotic you might be already aware of it but the GitHub Pages documentation of `raviger` is showing a mix of French and English pages in the side navigation, is that expected?

https://kyeotic.github.io/raviger/

![image](https://user-images.githubusercontent.com/1464666/117217232-6591df80-ae44-11eb-9c1a-f34a732c8973.png)

**Comment by kyeotic** [comment]
Wtf?! No, thank you for reporting this

**Comment by kyeotic** [comment]
Somehow the old submodule for the hugo theme was causing this. It has been fixed
