### ISSUE TITLE
Ship sourcemaps in package

### ISSUE THREAD

**Issue by dave-irvine** [kyeotic/raviger#91]
Hi!

I've run into a couple of cases now where Raviger has been throwing an error and I can't view the source to debug :(

I can see in your Rollup config you are building sourcemaps, so I'm wondering if you can ship those in the bundle somehow so that I can properly debug during development?

Thanks!

**Comment by n33pm** [comment]
shipped with #83

hopefully it will come soon 🥴

**Comment by kyeotic** [comment]
Yes, I will add this in the next version

**Comment by kyeotic** [comment]
sourcemaps are included in [2.3.1](https://github.com/kyeotic/raviger/releases/tag/v2.3.1)
