### ISSUE TITLE
Redirect does not render component that matches route

### ISSUE THREAD

**Issue by roypearce** [kyeotic/raviger#94]
Hey Tim, I'm starting up a new repo and encountering this issue that I've reproduced in this codesandbox https://codesandbox.io/s/stoic-cori-xol1o?file=/src/App.tsx

Basically I want to use `Redirect` to match any non-matching routes on page load and redirect to a specific route that has a component. What I'm seeing though is that if there are any paths that match the `Redirect`, the location in the url updates as expected, but the component that matches that route does not render.

Hopefully I'm missing something, but I can't find anything that might help. Thanks.

**Comment by kyeotic** [comment]
This is a bit odd, since when using the `navigate` function in the button, instead of `window.location`,  [the buttons work](https://codesandbox.io/s/bold-herschel-eonso?file=/src/App.tsx) to redirect and render the correct content. But `<Redirect>` uses `navigate` internally...

**Comment by roypearce** [comment]
Based on your explanation it definitely seems like something is not set up that is expected to be there for it to work correctly. 

Looking through the chain of events, the one thing that seems suspect that could fit the pattern of the issue is this https://github.com/kyeotic/raviger/blob/main/src/path.js#L100 

The other would be to check if the `popstate` event in `useLocationChange` is set up when that first `navigate` is triggered. 

I'm swamped this week, but could do some real debugging next week if you'd like some help with this.

**Comment by kyeotic** [comment]
I was out of town over the weekend, sorry for the delay.

> Looking through the chain of events, the one thing that seems suspect that could fit the pattern of the issue is this https://github.com/kyeotic/raviger/blob/main/src/path.js#L100

That particular case is for `basePath` updates, which I don't think are connected here, though [this one](https://github.com/kyeotic/raviger/blob/main/src/path.js#L85) might be.

**Comment by kyeotic** [comment]
Sorry this took so long @roypearce, this was a real head-scratcher. Debugging shows everything fire as expected, but the `useState` update from `useLayoutEffect` doesn't result in a re-render for... reasons?

#95 fixes it, I will publish shortly

**Comment by kyeotic** [comment]
published under [2.4.2](https://github.com/kyeotic/raviger/releases/tag/v2.4.2)

**Comment by roypearce** [comment]
Awesome! Really appreciate it. It's a really interesting issue. Thanks for the fix 😃
